default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  variables:
    sql_mode: :default
  timeout: 5000

development:
  <<: *default
  database: pr_dev

test:
  <<: *default
  database: pr_test

production:
  <<: *default
  database: pr_production
